### ISSUE TITLE
At least with MSVC++, the crate-compiled version of METIS seems really slow

### ISSUE THREAD

**Issue by oisyn** [LIHPC-Computational-Geometry/metis-rs#19]
I was running into this with a graph I was passing to METIS. The part_kway function seems to take about 30 seconds, while the command line utility, built directly from the source, on the same graph takes less than a second.

I suspect it's missing some of the compile options or defines that a CMAKE-generated project is using. I will investigate.

**Comment by oisyn** [comment]
Hmm, I really thought that during my initial checks in `--release`, I had the same issue. But I can't repro that. The culprits seem to be the `NDEBUG` and `NDEBUG2` defines, but those are set when `debug_assertions` is not enabled.

Nevertheless, I'd like to suggest to always compile the library as release, regardless of the optimization level of Rust, and that you can explicitely opt-in to building a debug version if you want, either through a feature or an env var. Any thoughts?

**Comment by cedricchevalier19** [comment]
I think always build the optimized version of Metis makes more sense. We can add to the documentation how to change the option in the documentation but I think for debugging using a separate Metis should be a better idea.

Thank you for reporting and investigating this issue.

**Comment by oisyn** [comment]
Yeah, I agree that that makes the most sense.
