### ISSUE TITLE
Would it be possible to publish a new release

### ISSUE THREAD

**Issue by Jasper-Bekkers** [LIHPC-Computational-Geometry/metis-rs#22]
We're relying on 06d4b31 for ourselves and would like to see a newly released version of this crate with that change included, would that be possible? Thanks 🙏

**Comment by cedricchevalier19** [comment]
I will try to do a release by the end of the month.

**Comment by JMS55** [comment]
I also would super appreciate a release, for use in https://github.com/bevyengine/bevy/pull/10164.

**Comment by cedricchevalier19** [comment]
I have published a new release, version 0.2.0 of `metis`. I hope that it works for you.
Thank you for your interest and your patience.

**Comment by JMS55** [comment]
Yep that's perfect, thanks for the new release!

**Comment by JMS55** [comment]
I switched from this:
`metis = { git = "https://github.com/LIHPC-Computational-Geometry/metis-rs", rev = "dd74128", optional = true }`
To this:
`metis = { version = "0.2", optional = true }`
And now metis fails to build 🤔 

```
error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Z7" "-Brepro" "-I" "C:\\Users\\JMS\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\metis-sys-0.3.0\\../vendor\\metis/include" "-I" "C:\\Users\\JMS\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\metis-sys-0.3.0\\../vendor\\metis/libmetis" "-I" "C:\\Users\\JMS\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\metis-sys-0.3.0\\../vendor\\GKlib" "-I" "C:\\Users\\JMS\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\metis-sys-0.3.0\\../vendor\\GKlib/win32" "/FImath.h" "-DNDEBUG" "-DNDEBUG2" "-DIDXTYPEWIDTH=32" "-DREALTYPEWIDTH=32" "-DUSE_GKREGEX" "-DWIN32" "-D__thread=__declspec(thread)" "-DMSC" "-D_CRT_SECURE_NO_WARNINGS" "-FoC:\\Users\\JMS\\Projects\\bevy\\target\\release\\build\\metis-sys-d6c8548c841dfa43\\out\\lib\\ee6ef9ea489a5765-adapt.o" "-c" "C:\\Users\\JMS\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\metis-sys-0.3.0\\../vendor\\GKlib/win32\\adapt.c" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

**Comment by cedricchevalier19** [comment]
Oh, sorry about that @JMS55 . I will try to set up a windows CI as I do not have any windows machine to check on.
If you can provide the detailed error from ms C compiler, that can be very helpful.

**Comment by JMS55** [comment]
Same issue happens on linux https://paste.rs/tZYM3.txt

**Comment by Jasper-Bekkers** [comment]
> Same issue happens on linux https://paste.rs/tZYM3.txt. The `vendor` folder does not seem to exist unless you use metis-rs as a git dependency.

Make sure to clone the repo with submodules

**Comment by JMS55** [comment]
> Make sure to clone the repo with submodules
I'm not cloning the repo. The issue is depending on metis-rs as a regular dependency from crates.io fails to compile.

**Comment by cedricchevalier19** [comment]
I think the newer version fixes the issue. I have moved the `vendor` directory in `metis-sys` and I have checked that it is now present in the crate.
