### ISSUE TITLE
METIS is Apache 2.0 licensed exclusively

### ISSUE THREAD

**Issue by wlinna** [LIHPC-Computational-Geometry/metis-rs#35]
I noticed that you distribute `metis-rs` under both Apache 2.0 and MIT. However, [METIS FAQ](http://glaros.dtc.umn.edu/gkhome/metis/metis/faq?q=metis/metis/faq#distribute) states that you can distribute it under Apache 2.0. Just to be sure, I downloaded the sources, and it is only licensed under Apache 2.0.

Now I am not a lawyer.. perhaps it is okay to distribute bindings under different license. Regardless, distributing them under MIT is likely to confuse users who believe they can use the library-as-a-whole under MIT license.

Suggested changes:
- Remove LICENSE-MIT
- In Cargo.toml, change `license = "MIT OR Apache-2.0"` to `license = "Apache-2.0"`

**Comment by wlinna** [comment]
Thank you for the quick response :)

My paraphrasing indeed misses some important nuances. Should have quoted verbatim instead.

> It is not our job to state which terms the original library can be used under (and we're not doing that)

This is what I was thinking as well. Offering `metis-rs` under `MIT or Apache-2.0` indeed makes sense. The license of METIS could change in the future in theory, in which case it's good that `metis-rs` is already licensed under terms that work well with the rest of the Rust ecosystem.

The only downside in this arrangement is the little bit of difficulty it might add to the process.
For example, if someone had to avoid Apache 2.0 license for some reason, and tried to use `cargo deny` or similar tool, they would easily miss the fact that they are using METIS which is distributed under Apache 2.0. If you can and do distribute both `metis-rs` and `METIS` under MIT and Apache 2.0, that would resolve the issue completely (or so I think, but IANAL).

This doesn't matter to me personally though, because I wasn't planning to use `metis-rs`, at least not yet. I merely found it out of curiosity.

**Comment by dssgabriel** [comment]
Hello @wlinna,

I agree with the suggestions made by @imrn99. We should (a) keep the licensing of `metis-rs` under `MIT or Apache-2.0` and; (b) make it clear that _only_ the bindings are subject to this dual license, not METIS (which AFAIK, we do not redistribute ourselves within this project).

I understand your concerns about the exclusive Apache-2.0 license of METIS. Still, I would argue it is not our responsibility if users somehow have to avoid Apache-2.0: we only provide bindings, and as such, it's up to users to ensure they comply with METIS's licensing policy.

Moreover, the METIS project hasn't had significant contributions for several years now — the latest change was already over a year ago, and contributions in the past few years were bug fixes — so it's unlikely their license will change in the future.

Anyway, I believe the most qualified and experienced person to respond to this is @cedricchevalier19, I'll defer to his opinion.

**Comment by cedricchevalier19** [comment]
@wlinna thanks for reporting this. As suggested by @imrn99 we will update the README.

The main concern is using the vendored feature that is enabled by default, in this case we also provide Metis source code (as Apache-2.0) but it might be confusing for the user.
I do not think we can automatically handle this cleanly with cargo (like disabling `vendored` when only MIT).

Anyway, we just provide a wrapper and the crate name `metis-sys` is explicit enough to flag the project as dependent on an external library and others projects on crates.io package the same way.
